server:
  port: 8088
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: D:\GitHub\spring-cloud-demo\config-server\src\main\resources\config-repo
          searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8088
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8087/eureka/  #注册中心地址
      
   